[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://paws-connect.onrender.com/api/:splat"
  status = 200
  force = true
